services:
  - type: web
    name: intelli-rag-kubernetes-helpdesk
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    autoDeploy: true
    envVars:
      - key: BACKEND_URL
        value: http://127.0.0.1:8000
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_FALLBACK_API_KEY
        sync: false
      - key: PORTKEY_API_KEY
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: QDRANT_CLUSTER_ENDPOINT
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: LOGFIRE_TOKEN
        sync: false
      - key: LANGSMITH_TRACING
        value: "false"
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LANGSMITH_PROJECT
        value: intelli-rag
      - key: LANGSMITH_ENDPOINT
        value: https://api.smith.langchain.com
